# 1. Introduction
> Julia offers productivity, generality, performance

> looks like Python, feels like LISP, 



# 2. Jupyter Notebook

In [3]:
1 + 2

3

In [4]:
1 + 2;

In [6]:
?println # get help doc for a function

search: println printstyled print sprint isprint



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` followed by a newline. If `io` is not supplied, prints to [`stdout`](@ref).

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello, world")

julia> String(take!(io))
"Hello, world\n"
```


In [12]:
;ls

Intro_to_Julia.ipynb


# Getting Started

In [13]:
println("Hello World ", 42)

Hello World 42


In [15]:
x = 42
typeof(x)

Int64

In [16]:
π

π = 3.1415926535897...

In [18]:
parse(Int64, "1")

1

In [19]:
#= 
multiple comments
=#

# Strings

In [23]:
s1 = """This is a "string"

"""

"This is a \"string\"\n\n"

In [21]:
typeof('a')

Char

In [22]:
typeof("a")

String

In [24]:
x = 12
println("x = $x")

x = 12


In [25]:
s1 = "University"
s2 = " of Wisconsin "
println(string(s1, s2))

University of Wisconsin 


In [26]:
s1 * s2

"University of Wisconsin "

# Data Structure

In [27]:
t = ("Apple", "Pear")

("Apple", "Pear")

In [28]:
point = (x = 1, y = 2)

(x = 1, y = 2)

In [30]:
point.x

1

In [32]:
point[2]

2

In [33]:
Dict(1=>"1", 2=>"2")

Dict{Int64,String} with 2 entries:
  2 => "2"
  1 => "1"

In [36]:
lst = [1:4;]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [37]:
push!(lst, 3)

5-element Array{Int64,1}:
 1
 2
 3
 4
 3

In [38]:
x = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [39]:
y = x[:]

3-element Array{Int64,1}:
 1
 2
 3

In [40]:
y

3-element Array{Int64,1}:
 1
 2
 3

In [43]:
x = rand(4, 3)

4×3 Array{Float64,2}:
 0.04319    0.724058  0.613453 
 0.525343   0.623952  0.447038 
 0.548629   0.695724  0.193726 
 0.0659268  0.555095  0.0749055

In [44]:
x[:]

12-element Array{Float64,1}:
 0.04318997032186478
 0.525342759161936  
 0.5486291859204859 
 0.06592675876782406
 0.7240577777430637 
 0.6239515934853292 
 0.695723796371061  
 0.555095132339692  
 0.6134529805820099 
 0.44703758550474815
 0.19372601562025493
 0.07490547837929595

# Loop

In [45]:
x = rand(4, 3)

4×3 Array{Float64,2}:
 0.852704   0.0817371  0.525745
 0.50184    0.257217   0.308375
 0.527254   0.288412   0.222113
 0.0522761  0.336194   0.943897

In [46]:
m, n = size(x)

(4, 3)

In [47]:
for i=1:4, j=1:3
    println(x[i, j])
end

0.852704301066042
0.08173710775043652
0.5257451894471019
0.5018397824280363
0.2572173207241153
0.3083752988539372
0.5272538944498795
0.2884116457742163
0.22211270549608075
0.0522761005719492
0.33619406568097365
0.9438965524647254


# Conditionals

In [49]:
x = 1
println(x % 2 == 1 ? "x is odd" : "x is even")

x is odd


# Functions

In [52]:
sayhi(name) = println("Hi $name.")

sayhi (generic function with 1 method)

In [53]:
sayhi("Yaqi")

Hi Yaqi.


In [54]:
double = x -> 2x

#3 (generic function with 1 method)

In [55]:
double(3)

6

In [56]:
x = rand(4)

4-element Array{Float64,1}:
 0.44203180986454393
 0.4306765823245631 
 0.24658705158519756
 0.7057153037840092 

In [57]:
sort(x)

4-element Array{Float64,1}:
 0.24658705158519756
 0.4306765823245631 
 0.44203180986454393
 0.7057153037840092 

In [58]:
x

4-element Array{Float64,1}:
 0.44203180986454393
 0.4306765823245631 
 0.24658705158519756
 0.7057153037840092 

In [60]:
sort!(x)

4-element Array{Float64,1}:
 0.24658705158519756
 0.4306765823245631 
 0.44203180986454393
 0.7057153037840092 

In [61]:
map(double, [1, 2, 3])

3-element Array{Int64,1}:
 2
 4
 6

In [63]:
map(x -> x % 2 == 1, [1, 2, 34])

3-element Array{Bool,1}:
  true
 false
 false

In [64]:
broadcast(double, [1, 2, 3])

3-element Array{Int64,1}:
 2
 4
 6

In [65]:
double.([1, 2, 3])

3-element Array{Int64,1}:
 2
 4
 6

In [66]:
using Pkg
Pkg.add("Example")

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 % Resolving package versions...
 Installed Example ─ v0.5.1
  Updating `~/.julia/environments/v1.0/Project.toml`
  [7876af07] + Example v0.5.1
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [7876af07] + Example v0.5.1


In [67]:
using Example

┌ Info: Precompiling Example [7876af07-990d-54b4-ab0e-23690620f79a]
└ @ Base loading.jl:1192


In [68]:
hello("sa")

"Hello, sa"

In [70]:
s = rand(10^7);

In [72]:
@time sum(s)

  0.004823 seconds (5 allocations: 176 bytes)


5.000011708715703e6